version: "3"
services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  sqs:
    image: softwaremill/elasticmq
    hostname: sqs
    ports:
      - 9324:9324
    volumes:
      - /etc/localtime:/etc/localtime

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime
    depends_on:
      - db
      - sqs
      - statsd-exporter

#  worker:
#    env_file:
#      - docker/dev/docker.env
#    build:
#      context: ./
#      dockerfile: docker/dev/worker/Dockerfile
#    depends_on:
#      - django
#    volumes:
#      - .:/code
#
#  worker_py3_8:
#    env_file:
#      - docker/dev/docker.env
#    build:
#      context: ./
#      dockerfile: docker/dev/worker_py3.8/Dockerfile
#    depends_on:
#      - django
#    volumes:
#      - .:/code

#  nodejs:
#    hostname: nodejs
#    build:
#      context: ./
#      dockerfile: docker/dev/nodejs/Dockerfile
#      args:
#        NODE_ENV: development
#    environment:
#      NODE_ENV: development
#    ports:
#      - "8888:8888"
#      - "35729:35729"
#    volumes:
#      - .:/code
#      - /code/node_modules
#      - /code/bower_components

  frontend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/dev/frontend/Dockerfile
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
    ports:
      - "8888:8888"
    volumes:
      - ./frontend:/code
      - /etc/localtime:/etc/localtime
    depends_on:
      - django

  statsd-exporter:
    hostname: statsd
    image: prom/statsd-exporter:latest
    command:
      - '--log.level=info'
      - '--web.telemetry-path=/statsd/metrics'
    ports:
      - '9125:9125'
      - '9102:9102'
    volumes:
      - /etc/localtime:/etc/localtime
